In [1]:
import pandas as pd
from numpy import asarray
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('heart_2020_cleaned.csv')

In [3]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [4]:
encoder = OneHotEncoder(handle_unknown='ignore')

In [5]:
heart_disease_df= pd.DataFrame(encoder.fit_transform(df[['HeartDisease']]).toarray())
heart_disease_name = ["Heart disease(No)", "Heart disease(Yes)"]
heart_disease_df.columns = heart_disease_name
print(heart_disease_df.shape)
heart_disease_df.head()

(319795, 2)

   Heart disease(No)  Heart disease(Yes)
0                1.0                 0.0
1                1.0                 0.0
2                1.0                 0.0
3                1.0                 0.0
4                1.0                 0.0

In [6]:
smoking_df= pd.DataFrame(encoder.fit_transform(df[['Smoking']]).toarray())
smoking_name = ["Smoke(No)", "Somke(Yes)"]
smoking_df.columns = smoking_name
print(smoking_df.shape)
smoking_df.head()

(319795, 2)

   Smoke(No)  Somke(Yes)
0        0.0         1.0
1        1.0         0.0
2        0.0         1.0
3        1.0         0.0
4        1.0         0.0

In [7]:
alcohol_drinking_df= pd.DataFrame(encoder.fit_transform(df[['AlcoholDrinking']]).toarray())
alcohol_drinking_name = ["AlcoholDrinking(No)", "AlcoholDrinking(Yes)"]
alcohol_drinking_df.columns = alcohol_drinking_name
print(alcohol_drinking_df.shape)
alcohol_drinking_df.head()

(319795, 2)

   AlcoholDrinking(No)  AlcoholDrinking(Yes)
0                  1.0                   0.0
1                  1.0                   0.0
2                  1.0                   0.0
3                  1.0                   0.0
4                  1.0                   0.0

In [8]:
stroke_df = pd.DataFrame(encoder.fit_transform(df[['Stroke']]).toarray())
stroke_name = ["Stroke(No)", "Stroke(Yes)"]
stroke_df.columns = stroke_name
print(stroke_df.shape)
stroke_df.head()

(319795, 2)

   Stroke(No)  Stroke(Yes)
0         1.0          0.0
1         0.0          1.0
2         1.0          0.0
3         1.0          0.0
4         1.0          0.0

In [9]:
diff_walking_df = pd.DataFrame(encoder.fit_transform(df[['DiffWalking']]).toarray())
diff_walking_name = ["DiffWalking(No)", "DiffWalking(Yes)"]
diff_walking_df.columns = diff_walking_name
print(diff_walking_df.shape)
diff_walking_df.head()

(319795, 2)

   DiffWalking(No)  DiffWalking(Yes)
0              1.0               0.0
1              1.0               0.0
2              1.0               0.0
3              1.0               0.0
4              0.0               1.0

In [10]:
sex_df = pd.DataFrame(encoder.fit_transform(df[['Sex']]).toarray())
sex_name = ["Female", "Male"]
sex_df.columns = sex_name
print(sex_df.shape)
sex_df.head()

(319795, 2)

   Female  Male
0     1.0   0.0
1     1.0   0.0
2     0.0   1.0
3     1.0   0.0
4     1.0   0.0

In [11]:
df["AgeCategory"].unique()

array(['55-59', '80 or older', '65-69', '75-79', '40-44', '70-74',
       '60-64', '50-54', '45-49', '18-24', '35-39', '30-34', '25-29'],
      dtype=object)

In [12]:
df['AgeCategory'] = df['AgeCategory'].replace("80 or older", "80")
df['AgeCategory'] = df['AgeCategory'].str.rsplit("-")
df['AgeCategory'] = df['AgeCategory'].str[0]
df['AgeCategory'] = df['AgeCategory'].astype('float64')
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55.0,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80.0,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65.0,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75.0,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40.0,White,No,Yes,Very good,8.0,No,No,No

In [13]:
def one_hot_encode(x:np.ndarray):
    uni = np.unique(x)
    print(uni)
    result = np.zeros((len(x), len(uni)))
    for i in range(len(x)):
        for j in range(len(uni)):
            if x[i] == uni[j]:
                result[i][j] = 1;
                
    return result

In [14]:
race_arr = pd.DataFrame(df['Race']).to_numpy()
one_hot_race = one_hot_encode(race_arr)
race_df = pd.DataFrame(one_hot_race, columns = ['American Indian/Alaskan Native', 'Asian', 'Black', 'Hispanic', 'Other',
 'White'])
race_df.head()

['American Indian/Alaskan Native' 'Asian' 'Black' 'Hispanic' 'Other'
 'White']

   American Indian/Alaskan Native  Asian  Black  Hispanic  Other  White
0                             0.0    0.0    0.0       0.0    0.0    1.0
1                             0.0    0.0    0.0       0.0    0.0    1.0
2                             0.0    0.0    0.0       0.0    0.0    1.0
3                             0.0    0.0    0.0       0.0    0.0    1.0
4                             0.0    0.0    0.0       0.0    0.0    1.0

In [15]:
diabetic_arr = pd.DataFrame(df['Diabetic']).to_numpy()
one_hot_diabetic = one_hot_encode(diabetic_arr)
diabetic_df = pd.DataFrame(one_hot_diabetic, columns = ['Diabetic(No)', 'Diabetic(No, borderline diabetes)', 'Diabetic(Yes)', 'Diabetic(Yes, during pregnancy)'])
diabetic_df.head()

['No' 'No, borderline diabetes' 'Yes' 'Yes (during pregnancy)']

,Diabetic(No),"Diabetic(No, borderline diabetes)",Diabetic(Yes),"Diabetic(Yes, during pregnancy)"
0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0

In [16]:
physical_activity_df= pd.DataFrame(encoder.fit_transform(df[['PhysicalActivity']]).toarray())
physical_activity_name = ["Physical Activity(No)", "Physical Activity(Yes)"]
physical_activity_df.columns = physical_activity_name
print(physical_activity_df.shape)
physical_activity_df.head()

(319795, 2)

   Physical Activity(No)  Physical Activity(Yes)
0                    0.0                     1.0
1                    0.0                     1.0
2                    0.0                     1.0
3                    1.0                     0.0
4                    0.0                     1.0

In [17]:
gen_health_arr = pd.DataFrame(df['GenHealth']).to_numpy()
one_hot_gen_health = one_hot_encode(gen_health_arr)
gen_health_df = pd.DataFrame(one_hot_gen_health, columns = ['GenHealth(Excellent)', 'GenHealth(Fair)', 
                                                            'GenHealth(Good)', 'GenHealth(Poor)', 'GenHealth(Very good)'])

['Excellent' 'Fair' 'Good' 'Poor' 'Very good']

In [18]:
asthma_df= pd.DataFrame(encoder.fit_transform(df[['Asthma']]).toarray())
asthma_name = ["Asthma(No)", "Asthma(Yes)"]
asthma_df.columns = asthma_name
print(asthma_df.shape)
asthma_df.head()

(319795, 2)

   Asthma(No)  Asthma(Yes)
0         0.0          1.0
1         1.0          0.0
2         0.0          1.0
3         1.0          0.0
4         1.0          0.0

In [19]:
kidney_disease_df= pd.DataFrame(encoder.fit_transform(df[['KidneyDisease']]).toarray())
kidney_disease_name = ["KidneyDisease(No)", "KidneyDisease(Yes)"]
kidney_disease_df.columns = kidney_disease_name
print(kidney_disease_df.shape)
kidney_disease_df.head()

(319795, 2)

   KidneyDisease(No)  KidneyDisease(Yes)
0                1.0                 0.0
1                1.0                 0.0
2                1.0                 0.0
3                1.0                 0.0
4                1.0                 0.0

In [20]:
skin_cancer_df= pd.DataFrame(encoder.fit_transform(df[['SkinCancer']]).toarray())
skin_cancer_name = ["SkinCancer(No)", "SkinCancer(Yes)"]
skin_cancer_df.columns = skin_cancer_name
print(skin_cancer_df.shape)
skin_cancer_df.head()

(319795, 2)

   SkinCancer(No)  SkinCancer(Yes)
0             0.0              1.0
1             1.0              0.0
2             1.0              0.0
3             0.0              1.0
4             1.0              0.0

In [21]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55.0,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80.0,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65.0,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75.0,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40.0,White,No,Yes,Very good,8.0,No,No,No

In [22]:
df = df.drop(['HeartDisease', 'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex', 'Race', 'Diabetic', 
        'PhysicalActivity', 'GenHealth', 'Asthma', 'KidneyDisease', 'SkinCancer'], axis=1)
df.head()

     BMI  PhysicalHealth  MentalHealth  AgeCategory  SleepTime
0  16.60             3.0          30.0         55.0        5.0
1  20.34             0.0           0.0         80.0        7.0
2  26.58            20.0          30.0         65.0        8.0
3  24.21             0.0           0.0         75.0        6.0
4  23.71            28.0           0.0         40.0        8.0

In [23]:
df = pd.concat([df, heart_disease_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0

In [24]:
df = pd.concat([df, smoking_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0

In [25]:
df = pd.concat([df, alcohol_drinking_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),AlcoholDrinking(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0

In [26]:
df = pd.concat([df, stroke_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),AlcoholDrinking(Yes),Stroke(No),Stroke(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [27]:
df = pd.concat([df, diff_walking_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),AlcoholDrinking(Yes),Stroke(No),Stroke(Yes),DiffWalking(No),DiffWalking(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [28]:
df = pd.concat([df, sex_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),AlcoholDrinking(Yes),Stroke(No),Stroke(Yes),DiffWalking(No),DiffWalking(Yes),Female,Male
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0

In [29]:
df = pd.concat([df, race_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,DiffWalking(No),DiffWalking(Yes),Female,Male,American Indian/Alaskan Native,Asian,Black,Hispanic,Other,White
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
df = pd.concat([df, diabetic_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,American Indian/Alaskan Native,Asian,Black,Hispanic,Other,White,Diabetic(No),"Diabetic(No, borderline diabetes)",Diabetic(Yes),"Diabetic(Yes, during pregnancy)"
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [31]:
df = pd.concat([df, physical_activity_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,Black,Hispanic,Other,White,Diabetic(No),"Diabetic(No, borderline diabetes)",Diabetic(Yes),"Diabetic(Yes, during pregnancy)",Physical Activity(No),Physical Activity(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0

In [32]:
df = pd.concat([df, asthma_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,Other,White,Diabetic(No),"Diabetic(No, borderline diabetes)",Diabetic(Yes),"Diabetic(Yes, during pregnancy)",Physical Activity(No),Physical Activity(Yes),Asthma(No),Asthma(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [33]:
df = pd.concat([df, gen_health_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,"Diabetic(Yes, during pregnancy)",Physical Activity(No),Physical Activity(Yes),Asthma(No),Asthma(Yes),GenHealth(Excellent),GenHealth(Fair),GenHealth(Good),GenHealth(Poor),GenHealth(Very good)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [34]:
df = pd.concat([df, kidney_disease_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,Physical Activity(Yes),Asthma(No),Asthma(Yes),GenHealth(Excellent),GenHealth(Fair),GenHealth(Good),GenHealth(Poor),GenHealth(Very good),KidneyDisease(No),KidneyDisease(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [35]:
df = pd.concat([df, skin_cancer_df], axis=1, join='inner')
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),...,Asthma(Yes),GenHealth(Excellent),GenHealth(Fair),GenHealth(Good),GenHealth(Poor),GenHealth(Very good),KidneyDisease(No),KidneyDisease(Yes),SkinCancer(No),SkinCancer(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

# Dataframe after encoding:

In [38]:
pd.set_option('display.max_columns', None)
df.head()

,BMI,PhysicalHealth,MentalHealth,AgeCategory,SleepTime,Heart disease(No),Heart disease(Yes),Smoke(No),Somke(Yes),AlcoholDrinking(No),AlcoholDrinking(Yes),Stroke(No),Stroke(Yes),DiffWalking(No),DiffWalking(Yes),Female,Male,American Indian/Alaskan Native,Asian,Black,Hispanic,Other,White,Diabetic(No),"Diabetic(No, borderline diabetes)",Diabetic(Yes),"Diabetic(Yes, during pregnancy)",Physical Activity(No),Physical Activity(Yes),Asthma(No),Asthma(Yes),GenHealth(Excellent),GenHealth(Fair),GenHealth(Good),GenHealth(Poor),GenHealth(Very good),KidneyDisease(No),KidneyDisease(Yes),SkinCancer(No),SkinCancer(Yes)
0,16.60,3.0,30.0,55.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,20.34,0.0,0.0,80.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,65.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,24.21,0.0,0.0,75.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,23.71,28.0,0.0,40.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0